version: "3.3"

services:

  zeppelin-starter:
    image: sqooba/zeppelin-starter
    environment:
      - ZEPPELIN_LOG_DIR=/zeppelin/logs
      - ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebooks
      - SPARK_SUBMIT_OPTIONS='--conf spark.sql.warehouse.dir=/zeppelin/spark-warehouse'
    ports:
      - "${ZEPPELIN_PORT}:8080" # zeppelin ui
      - "${SPARK_UI_PORT}:4040" # spark ui
    networks:
      - zeppelinnet
    volumes:
      - ${ZEPPELIN_ROOT_DIR}/data:/zeppelin/data
      - ${ZEPPELIN_ROOT_DIR}/logs:/zeppelin/logs
      - ${ZEPPELIN_ROOT_DIR}/bootstrap:/zeppelin/bootstrap:ro
      - ${ZEPPELIN_ROOT_DIR}/notebooks:/zeppelin/notebooks
      - ${ZEPPELIN_ROOT_DIR}/spark-warehouse:/zeppelin/spark-warehouse

networks:
  zeppelinnet:
    driver: bridge